### ISSUE TITLE
Make all call to ocaml through ocamfind

### ISSUE THREAD

**Issue by pirbo** [mjambon/atd#10]
Repository whitequark/opam-cross-windows offers a way to cross compile ocaml code for windows. It works by providing an alternative toolchain to ocamlfind so that `"OCAMLFIND_TOOLCHAIN=windows" ocamlfind opt ...` generates windows binaries.

For this purpose, it is convenient that any call to ocaml\* goes through ocamlfind which is the case here everywhere but for 2 instances. I've made the trivial patch:
https://github.com/whitequark/opam-cross-windows/blob/master/packages/atd-windows.1.2.0/files/patches/ocamlc_config_through_ocamlfind.patch and I forward it here for inclusion (if relevant).

**Comment by mjambon** [comment]
Thanks!
