### ISSUE TITLE
tag_field with varying key for value field

### ISSUE THREAD

**Issue by mjambon** [mjambon/atd#102]
_From @antoine1fr on March 29, 2015 18:14_

Hi,

I'm using a RESTful API which can return the following results:

``` json
{
  "type": "a",
  "a" : {...}
}
```

OR

``` json
{
  "type": "b",
  "b" : {...}
}
```

As you can see, the key of the field containing the value can change.

Is it currently possible to handle such a scenario with the tag_field feature?

_Copied from original issue: mjambon/atdgen#30_

**Comment by mjambon** [comment]
No but it would be useful.

A solution is possible using `wrap`, it's just more complicated than it should be. I'll try to post it a bit later.

**Comment by mjambon** [comment]
Here is the promised solution. It uses two atd files instead of just one, and an extra ml module that goes in-between (in dependency order):
- `x1.atd` contains the type definition that matches closely the json representation, using two optional fields `a` and `b`.
- `wrapped.ml` provides the nice variant type we wish to use instead of the record with optional fields; it provides `wrap` and `unwrap` functions that will be used during the serialization and deserialization process.
- `x2.atd` contains an atd definition that specifies that we don't want to use the naive type defined in `x1.atd` but instead wrap it in the type defined in `wrapped.ml`.

The reason for having two separate atd files is that the `Wrapped` module depends on the concrete representation of the low-level record defined in `x1_t.mli` but `x2_t.mli` depends on type defined in `wrapped.ml`.

File `x1.atd`:

``` ocaml
type t = {
  type_ <json name="type">: string;
  ?a: a option;
  ?b: b option;
}
  (* Type used during only serialization/deserialization *)

type a = int
type b = bool
```

File `wrapped.ml`:

``` ocaml
open X1_t (* makes record fields visible *)

type t = [
  | `A of X1_t.a
  | `B of X1_t.b
]

let extract name = function
  | Some x -> x
  | None -> failwith ("Missing field " ^ name)

let wrap (x: X1_t.t): t =
  match x.type_ with
  | "a" -> `A (extract "a" x.a)
  | "b" -> `B (extract "b" x.b)
  | s -> failwith ("Illegal field " ^ s)

let empty = {
  type_ = "";
  a = None;
  b = None;
}

let unwrap (x: t): X1_t.t =
  match x with
  | `A a -> { empty with type_ = "a"; a = Some a }
  | `B b -> { empty with type_ = "b"; b = Some b }
```

File `x2.atd`:

``` ocaml
type raw <ocaml from="X1" t="t"> = abstract

type t = raw wrap <ocaml module="Wrapped">
  (* Proper OCaml variant, abstracted away *)

(* Here you can add type definitions that use our wrapped type t *)
```

Finally, some code to close the demo. This is file `main.ml`:

``` ocaml
let main () =
  let x: X2_t.t = Ag_util.Json.from_channel X2_j.read_t stdin in
  Ag_util.Json.to_channel X2_j.write_t stdout x

let () = main ()
```

All of this can be compiled with the following commands:

```
atdgen -t x1.atd
atdgen -j -j-std x1.atd
atdgen -t x2.atd
atdgen -j -j-std x2.atd
ocamlfind opt -o tagged \
  x1_t.mli x1_t.ml \
  x1_j.mli x1_j.ml \
  wrapped.ml \
  x2_t.mli x2_t.ml \
  x2_j.mli x2_j.ml \
  main.ml \
  -package atdgen -linkpkg
```

The program reads a json record on stdin and echoes it back:

```
$ ./tagged 
{ "type": "a", "a": 123 }
{"type":"a","a":123}
```

**Comment by mjambon** [comment]
_From @antoine1fr on March 30, 2015 8:39_

Many thanks for this quick and complete answer, I'll try it ASAP !

**Comment by mjambon** [comment]
_From @dsheets on April 1, 2015 16:36_

I'm reasonably certain that you can use `tag_field` to achieve this but it would result in types that are uglier than the wrap solution (and have invariants not checked by OCaml's type system) and you'd need to create _a different type for each constructor_. Something like:

```
type tag = [ A | B ]
type a = [ A of blah | B ]
type b = [A | B of blah ]

type multi_constr = {
  tag : tag;
  a : a <json tag_field="tag">;
  b : b <json tag_field="tag">;
}
```

This may be suitable or it may be horrible depending on your use case. I've not tested this example but it is essentially `multi_constr_record` from `test/test3j.atd` and `test/test_atdgen_main.ml:461`.

**Comment by mjambon** [comment]
This will be solved with json adapters (atd > 1.13).

**Comment by mjambon** [comment]
atd 2.0.0 with support for [json adapters](https://mjambon.github.io/atdgen-doc/atdgen#field-adapter.ocaml) has been released. Let us know if you encounter difficulties.

**Comment by rauanmayemir** [comment]
How would this work if I needed to use proper `a` and `b` parsers? (not just option unwrapping, but preferably generated `read_a` and `read_b` decoders from x1)
I'm having a bit of a cyclic dependency issue.

As for json adapters, I couldn't make it work with bucklescript, annotations are just ignored.
