### ISSUE TITLE
Automate the approval of new generated test code

### ISSUE THREAD

**Issue by mjambon** [mjambon/atd#111]
Currently, `make tests` compares the code generated by the test suite and reports any difference with the previous version as an error. I quite like it, but it would be good to have a quick way to approve all or individual changes.

See also https://github.com/mjambon/atd/issues/56

**Comment by rgrinberg** [comment]
Doesn't `$ jbuilder runtest --auto-promote` accomplish this?

**Comment by mjambon** [comment]
oh, that's awesome!
