### ISSUE TITLE
Make a proper public announcement for atd 1.13.0

### ISSUE THREAD

**Issue by mjambon** [mjambon/atd#112]
We should announce this release on https://discuss.ocaml.org/, at least because people are unaware of the existence of atdgen. They use straight yojson, which has a more evocative name.

@rgrinberg if you're interested in making this announcement, go for it.

**Comment by mjambon** [comment]
_Draft_
Subject: ATD - static types for json APIs, v1.13.0

We've made a lot of internal changes to the ATD suite of tools, including atdgen. Atdgen takes is a full-featured program that takes as input type definitions and derives OCaml parsers and serializers for json. For example,

```
type hello = {
  greeting : string;
  ?fruit : fruit option;
}

type fruit = [ Peach | Cherry ]
```
results in two OCaml functions of the following types:
```
val hello_of_string : string -> hello
val string_of_hello : greeting:string -> ?fruit:fruit -> unit -> string
```

The purpose of the announcement is primarily to bring people's attention to the existence of this tool, which most people should be using rather than yojson (the parser and AST-handling library on which atdgen relies).

This is a stable release available from opam, and the changes are mostly internal. Different tools relying on atd have been consolidated into one repo, efforts are ongoing to make the codebase more accessible, and [new, exciting features are being developed](https://github.com/mjambon/atd/issues)!

**Comment by mjambon** [comment]
I'll post this in an hour. There are 2 URLs, toward the bottom that will take people where I want to: contributors and issues. There's no link to the main page, but that would be too many links.

Hopefully people will click and find the documentation?

**Comment by rgrinberg** [comment]
Thanks for writing this. I think adding a link to the documentation would be helpful as well because we did move the location of the docs.

**Comment by mjambon** [comment]
I added links to the new docs from the email and from the main readme. Link formatting needs fixing and atdgen's manual needs to be added (https://github.com/mjambon/atd/issues/109); hopefully we can get some help with that.
