### ISSUE TITLE
Removing topkg setup

### ISSUE THREAD

**Issue by mjambon** [mjambon/atd#122]
I already botched the 1.13.0 release due to not understanding how topkg works (`Atdgen_runtime.Version.version` is `"%%VERSION%%"`). topkg in its current state is too much overhead for little benefits. Following the steps listed by `topkg release help` fails so we have to pick and choose which steps to perform, which we have to document internally anyway. Also, we can no longer take advantage of github's automatic tarballs derived from tagged commits. Now we have to use the tarball created by topkg and I don't know how and where to upload it.

I'm going to remove the topkg setup for the 2.0.0 release and I guess I need to somehow release 1.13.1 to fix the runtime version problem. I'm not opposed to using it again in the future if/when it makes things more automated and more reliable.

**Comment by rgrinberg** [comment]
> I already botched the 1.13.0 release due to not understanding how topkg works (Atdgen_runtime.Version.version is "%%VERSION%%"

Could you describe the problem a bit more? It's true that this a topkg convention, but it's actually dune that does the substitution of the `%%VERSION%%` variable in the `$ jbuilder subst` step. I'm not sure how to address the problem of pinning reflecting a correct version number (one that contains a git commit suffix) without this mechanism.

> Also, we can no longer take advantage of github's automatic tarballs derived from tagged commits

On the other hand, we benefit from not having to deal with github changing your tarballs (and hence signatures) under the hood. This happens rarely, but it has happened enough that it's a noticeable churn in opam-repository.

> Now we have to use the tarball created by topkg and I don't know how and where to upload it.

I think `$ topkg publish distrib` should take of this step.

> I'm going to remove the topkg setup for the 2.0.0 release and I guess I need to somehow release 1.13.1 to fix the runtime version problem. I'm not opposed to using it again in the future if/when it makes things more automated and more reliable.

There's now https://github.com/samoht/dune-release which forks topkg to simplify it for dune packages. Perhaps we can reconsider it at this point.

**Comment by mjambon** [comment]
ok, thanks for those details. `topkg release help` mentions this:
```
       topkg distrib       # Create the distribution archive
       topkg publish       # Publish it on the WWW with its documentation
```
`topkg publish` fails with:
```
...
odoc should not generate html but will for the time being...
        odoc _doc/_html/atdgen/Atdgen__Version/.jbuilder-keep,_doc/_html/atdgen/Atdgen__Version/index.html
odoc should not generate html but will for the time being...
[ERROR] Variable odig:etc not found
topkg: [ERROR] run ['opam' 'config' 'var' 'odig:etc']: exited with 5
topkg: [ERROR] run ['topkg' 'doc']: exited with 3
```
However `topkg publish distrib` prompts me for my github password, which looks reasonable so I'm trying this.

**Comment by mjambon** [comment]
`topkg publish distrib` is promising but I'm getting a 401 Unauthorized because I use 2-factor authentication.
```
$ topkg publish distrib
Everything up-to-date
Enter host password for user 'mjambon':
toy-github-topkg-delegate: [ERROR] Could not find release id in
                                   response:
                                   HTTP/1.1 401 Unauthorized
                                   Date: Sun, 03 Jun 2018 06:39:26
                                   GMT
                                   Content-Type: application/json;
                                   charset=utf-8
                                   Content-Length: 170
                                   Server: GitHub.com
                                   Status: 401 Unauthorized
                                   X-GitHub-OTP: required;
                                   app
                                   X-GitHub-Media-Type: github.v3;
                                   format=json
                                   X-RateLimit-Limit:
                                   60
                                   X-RateLimit-Remaining:
                                   59
                                   X-RateLimit-Reset:
                                   1528011566
                                   Access-Control-Expose-Headers: ETag, Link,
                                   Retry-After, X-GitHub-OTP,
                                   X-RateLimit-Limit, X-RateLimit-Remaining,
                                   X-RateLimit-Reset, X-OAuth-Scopes,
                                   X-Accepted-OAuth-Scopes,
                                   X-Poll-Interval
                                   Access-Control-Allow-Origin:
                                   *
                                   Strict-Transport-Security:
                                   max-age=31536000; includeSubdomains;
                                   preload
                                   X-Frame-Options:
                                   deny
                                   X-Content-Type-Options:
                                   nosniff
                                   X-XSS-Protection: 1;
                                   mode=block
                                   Referrer-Policy: origin-when-cross-origin,
                                   strict-origin-when-cross-origin
                                   Content-Security-Policy: default-src
                                   'none'
                                   X-Runtime-rack:
                                   0.047665
                                   X-GitHub-Request-Id:
                                   8D96:0FFB:291D87E:2E640EC:5B138D1E
                                   
                                   {
                                     "message": "Must specify two-factor
                                   authentication OTP code.",
                                     "documentation_url":
                                   "https://developer.github.com/v3/auth#working-with-two-factor-authentication"
                                   }
                                   .
topkg: [ERROR] Delegate toy-github-topkg-delegate errored with 2
```

**Comment by rgrinberg** [comment]
I'm not 100% sure how to fix the 2FA issue, but you can try creating a custom github token and using it manually like this:

```
TOPKG_GITHUB_AUTH="mjambon:foobartokencreateyourown" topkg publish distrib
```

You you can see how to get a token here: https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

**Comment by mjambon** [comment]
ok, we have a release: https://github.com/mjambon/atd/releases/tag/2.0.0

So we're keeping topkg support after all. I'll document the instructions to make releases.
