### ISSUE TITLE
Clarify documentation

### ISSUE THREAD

**Issue by mjambon** [mjambon/atd#134]
@shonfeder wrote in https://github.com/mjambon/atd/issues/33#issuecomment-398278382

> I think the documentation for validation may be out of date? (The docs say valid annotations on a type t should result in validators of the type `t -> bool`, but it looks like validators are actually of type `path -> t -> Validation.error option`). If this correct, I can make a PR to update the docs.

**Comment by shonfeder** [comment]
I should be able to take care of these simple corrections.
