### ISSUE TITLE
Do not trigger warnings

### ISSUE THREAD

**Issue by Chris00** [mjambon/atd#146]
With the default (development) settings of Dune, fatal warnings will be triggered for files produced by `atdgen` for unused values.  The simpler may be to put an annotation `[@@warning ...]` at the beginning of the generated files.  Other possibilities may be to start all functions that will not end up in the signature with `_` or to make an analysis and actually not write unused functions.

**Comment by mjambon** [comment]
The generated files currently start with `[@@@ocaml.warning "-27-32-35-39"]`. You can check for your specific version of atdgen with `echo 'type t = bool' | atdgen -j` and make sure it was compiled with the same version of ocaml as the generated code.

I think this should cover it but please let us know if a specific warning code needs to be added.

**Comment by Chris00** [comment]
Ah, OK, I was using an older version of atdgen.  Sorry for the disturbance.
