### ISSUE TITLE
Support for interpreting {"x":null} as {x = Some None}

### ISSUE THREAD

**Issue by mjambon** [mjambon/atd#18]
The goal of this feature is to support patch semantics for records. A patch record is a set of optional fields. The presence of a field in json indicates how to modify a certain field in some destination object. Given that the destination object itself may already have optional fields, we need a way to express "clear this field's value".

The problem is that until now, atdgen was treating a null json field as if the field was missing. Instead here, we want the null value of the field to indicate a request to clear or delete a field.

```ocaml
(* Type of the objects stored in our database *)
type t = {
  ?x : int option;
  ?y : int option;
  ?z : int option;
}
```

```ocaml
(* Request to modify some of the fields of an object *)
type t_patch = {
  ?x : int nullable option;
  ?y : int nullable option;
  ?z : int nullable option;
} <ocaml field_prefix="patch_"> <json keep_nulls>
```

Let's consider the following json patch:
```
{
  "x": 1, // request to set field x to 1
  "y": null // request to clear field y
  // implicit request to leave field z unchanged
}
```

It has the following OCaml representation:

```ocaml
{
  patch_x = Some (Some 1);
  patch_y = Some None;
  patch_z = None;
}
```

This gets us two levels of optionality (`_ option option`) in json, while staying idiomatic.

I'm about to implement this `keep_nulls` feature.

**Comment by cyberhuman** [comment]
This feature would be great to have! I've stumbled upon the `null` issue several times already, and so far I had to use some `wrap` hacks to get the `null` output by atdgen.
Will the `keep_nulls` attribute supported per field, so it is more flexible?

**Comment by mjambon** [comment]
It's going to be per record. We could also have a per-field override but I
don't think it's worth the complexity, unless someone can show an example
where this is useful.

**Comment by ygrek** [comment]
@mjambon ftr there was a bounty on this issue https://www.bountysource.com/issues/46455506-support-for-interpreting-x-null-as-x-some-none
Please feel free to claim it, otherwise bountysource will retain the money for themselves

**Comment by mjambon** [comment]
@ygrek done. Thank you for letting me know and thank you to the generous backer!
