### ISSUE TITLE
`Basic.json` or `Basic.t` for untyped JSON

### ISSUE THREAD

**Issue by jeromesimeon** [mjambon/atd#185]
I am migrating to the latest versions on opam (atdgen.2.0.0 and yojson.1.6.0). I have untyped json in parts of my ATD definitions. The following definition now raises warnings:

```
bash-3.2$ cat test_json.atd 
type json <ocaml module="Yojson.Basic" t="json"> = abstract
<doc text="Type of arbitrary JSON values.">
bash-3.2$ ocamlfind ocamlc -c test_json_j.mli -package atdgen 
File "test_json_j.mli", line 5, characters 12-29:
Warning 3: deprecated: Yojson.Basic.json
json types are being renamed and will be removed in the next Yojson major version. Use type t instead
bash-3.2$ ocamlfind ocamlc -c test_json_j.ml -package atdgen 
File "test_json_j.ml", line 5, characters 12-29:
Warning 3: deprecated: Yojson.Basic.json
json types are being renamed and will be removed in the next Yojson major version. Use type t instead
```

Switching to `t` instead of `json` doesn't seem to help:
```
bash-3.2$ cat test_t.atd 
type json <ocaml module="Yojson.Basic" t="t"> = abstract
<doc text="Type of arbitrary JSON values.">
bash-3.2$ atdgen -j -j-std test_t.atd 
bash-3.2$ ocamlfind ocamlc -c test_t_j.mli -package atdgen
bash-3.2$ ocamlfind ocamlc -c test_t_j.ml -package atdgen
File "test_t_j.ml", line 8, characters 2-22:
Error: Unbound value Yojson.Basic.write_t
Hint: Did you mean write_int?
```

I'm wondering if I'm doing the wrong thing, or if it's a mismatch between atd and yojson.

Is there any workaround? What is the correct way to define untyped JSON with the latest version?

**Comment by mjambon** [comment]
Yojson modules since 1.6.0 now provide type `t` and the legacy type `json` is deprecated. This needs to be fixed in atdgen. An immediate workaround is to use an earlier version of yojson. This should be done in opam-repository (I don't have time for it right now; someone else is welcome to do so). Another workaround would be to create your own Json module with the correct signature.

I'm not sure what a proper fix would look like.

**Comment by jeromesimeon** [comment]
Thanks for the quick response. I can't commit to putting work into this right now, but might give it a shot down the road.

As an aside I've been having issues downgrading to yojson.1.4.1 with the latest opam/ocaml as well...

**Comment by jeromesimeon** [comment]
I might try with creating my own Json module though. Looks like a reasonable route.

**Comment by NathanReb** [comment]
This will be fixed in `yojson` `1.7.0` which exposes `write_t` and `read_t` and is about to be released!

I think this can be closed!

**Comment by jeromesimeon** [comment]
👍 works for me. Thanks!

The documentation may need updating.

**Comment by jeromesimeon** [comment]
Everything works great with yojson.1.7.0:
```
bash-3.2$ cat test_t.atd 
type json <ocaml module="Yojson.Safe" t="t"> = abstract
<doc text="Type of arbitrary JSON values.">

bash-3.2$ atdgen -j -j-std test_t.atd  
bash-3.2$ ocamlfind ocamlc -c test_t_j.mli -package atdgen
bash-3.2$ ocamlfind ocamlc -c test_t_j.ml -package atdgen
```
