### ISSUE TITLE
string_of type that contain enum generate not valid JSON

### ISSUE THREAD

**Issue by gabrik** [mjambon/atd#186]
Hi all,

I have a type that contains an Enum

```
type virtual_network = {
  uuid : string;
  name : string;
  net_type : vn_type;
  is_mgmt : bool
}


type vn_type = [
  | ELINE
  | ELAN
 ] 
```

When I convert from OCaml type to JSON
```
let vn = {uuid="0987"; name="net1"; net_type=`ELAN; is_mgmt=false};;
let sn = FTypesJson.string_of_virtual_network vn;;
Printf.printf "\n%s\n" sn;;
{"uuid":"0987","name":"net1","net_type":<"ELAN">,"is_mgmt":false}
- : unit = ()
```

As you can see `"net_type":<"ELAN">` is not a valid JSON, if I try to use that string in python I got
```
>>> s = '{"uuid":"0987","name":"net1","net_type":<"ELAN">,"is_mgmt":false}'
>>> d = json.loads(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 41 (char 40)
```

Any ideas? 
I have tried using `<json open_enum>` but the result is always the same, I think I'm doing it wrong, suggestions?

**Comment by mjambon** [comment]
You have to use the `-j-std` option on the command line. This was a design mistake, sorry about that. We've been keeping it for backward-compatibility until an atdgen 2.x.x is released.

**Comment by gabrik** [comment]
@mjambon thanks! now it is ok!

**Comment by tcoopman** [comment]
I ran into the same issue, and `-j-std` seems to fix this indeed. But the output of the `j` files now have their own types? They are not pointing to the types in the `_t` files anymore?

**Comment by Khady** [comment]
hmm, the types in _j should still be the one in _t. At least that's why I have in my projects.

**Comment by tcoopman** [comment]
I'm using the latest 2.1 branch, so maybe it's something that's wrong in there?

**Comment by tcoopman** [comment]
Ah, it was not clear that I had to combine the flag `-j` and `-j-std`. This is working now
