### ISSUE TITLE
Variant keys in <json repr="object"> assoc lists

### ISSUE THREAD

**Issue by outkine** [mjambon/atd#193]
My program has a fixed set of "teams", represented by a variant. I want to allow a json type where each team is associated with a list of units, and an assoc list with `<json repr="object">` is perfect for this. 
```
type team = [ Red | Blue ]
type units_by_team = (team * unit list) list <json repr="object">
```
This, however, leads to a `Due to <json repr="object"> keys must be strings` error. I tried wrapping:
```
type units_by_team = (string * id list) list <json repr="object"> wrap
<ocaml t="(team * id list) list" wrap="List.map ~f:(
  fun (team, units) -> match team with
  | \"Blue\" -> (`Blue, units)
  | \"Red\" -> (`Red, units)
  | _ -> failwith \"Invalid team.\"
)" unwrap="List.map ~f:(
  fun (team, units) -> match team with
  | `Blue -> (\"Blue\", units)
  | `Red -> (\"Red\", units)
)">
```
But because atd doesn't see the `team` type, it generates a broken `_t` file where `team` is referenced before it is defined.

Since assoc lists with variant keys are supported in OCaml, why not support them in atd?

**Comment by mjambon** [comment]
The reason for not supporting this would be that it's not very useful.

You may want to consider the following workarounds:
* If the keys repeat, don't use a JSON object but an array of key/value pairs.
* If the keys are unique and optional, use a record type defined as follows:
```
type t = {
  ?blue : id list option;
  ?red : id list option;
}
```
or
```
type t = {
  ~blue : id list;
  ~red : id list;
}
```
