### ISSUE TITLE
Support for BuckleScript as a new codegen target

### ISSUE THREAD

**Issue by sgrove** [mjambon/atd#20]
I'm using [BuckleScript](http://bucklescript.github.io/bucklescript/Manual.html#_why_bucklescript) on the client, and ATD on the server (which is fantastic). Unfortunately, BS doesn't have an ATD-like library, which makes converting JSON into OCaml records (and back) very cumbersome.

I'm interested in using ATD to generate the boilerplate for the client in the same way I do for the server.

One caveat is that the browser already has a fantastic JSON-parser, so the generated code is more about plucking the values from the browser-parsed JSON, verifying the types, and returning an OCaml-record.

To give you and example, here's what parsing a JSON-string into a small, four-field record looks like right now (it's using the Reason syntax and BS library, but I hope it's clear enough):

```reason
let pluckField decoder field obj =>
  Option.getExn @@ decoder @@ Option.getExn @@ Js.Dict.get obj field;

let decodeJson str handler => {
  open Js.Json;
  let json =
    try (parseExn str) {
    | _ => raise (Failure "Error parsing API response JSON")
    };
  switch (decodeObject json) {
  | Some obj => handler obj
  | _ => raise (Failure "Couldn't decode JSON properly")
  }
};

type health = {accountCount: int, sessionCount: int, sessionsHealthy: bool, accountsHealthy: bool};

let healthOfJsonString jsonString =>
  Js.Json.(
    decodeJson
      jsonString
      (
        fun jsonObj => {
          let accountCount = int_of_float @@ pluckField decodeNumber "accounts_count" jsonObj;
          let sessionCount = int_of_float @@ pluckField decodeNumber "sessions_count" jsonObj;
          let accountsHealthy = Js.to_bool @@ pluckField decodeBoolean "accounts_healthy" jsonObj;
          let sessionsHealthy = Js.to_bool @@ pluckField decodeBoolean "sessions_healthy" jsonObj;
          ({accountCount, sessionCount, sessionsHealthy, accountsHealthy}: health)
        }
      )
  );
```

I'd like to generate something like the above (well, better eventually) using the ATD machinery. Where would you suggest I start?

**Comment by mjambon** [comment]
If the bucklescript values are straightforward, idiomatic javascript values, is there a way to tell bucklescript "here's a javascript object of this type, trust me I checked"? In this case all you need is a validator at the javascript level. The tool would take atd definitions and generate javascript code directly. What do you think?

I find that a good way to test such ideas is to write down examples for the various types that must be supported and sample representations in each language involved.

As for a code reference, I recommend looking into the implementation of [atdj](https://github.com/esperco/atdj), which is much plainer than atdgen. It also uses a separate json parser, much like what you're trying to achieve. Note that it creates new java objects, though; it's not just a validator.

**Comment by dysinger** [comment]
The code on atd master works. https://github.com/ahrefs/bs-atdgen-codec-runtime
We should close this issue soon.
