### ISSUE TITLE
Split runtime into own opam package

### ISSUE THREAD

**Issue by rgrinberg** [mjambon/atd#35]
There's a use case where users would like to vendor the generated code by atdgen into their repos. Unfortunately, this doesn't let you drop the dependency on atdgen as the runtime is still in atdgen itself. It would be nice if this was a separate package to allow this kind of use case. I'm proposing we split out the runtime into a `atdgen-runtime` package for this purpose.

**Comment by rgrinberg** [comment]
Another approach that can be taken here is moving the code generator to its own package. For example leave the runtime as `atdgen` but move the code generator to `atdgen-pp`. This is uglier naming wise, but I think it breaks less code in the short run. I'm thinking of all those people that are using `Atdgen\.` function currently (e.g. validation). But of course we can also we re-export all those symbols in `atdgen`.

**Comment by mjambon** [comment]
I like the `atdgen`/`atdgen-runtime` split and I don't understand how the other proposal would be better (seems worse to me). I'll continue the discussion on the pull request #36 (if needed).

**Comment by rgrinberg** [comment]
This is fixed in master.
