### ISSUE TITLE
Plan for more flexible support for variants + getting rid of Obj.magic

### ISSUE THREAD

**Issue by mjambon** [mjambon/atd#42]
Many json APIs out there use various conventions for representing sum types (variants), and supporting them all has been a pain point for all consumers of external APIs. Support for one specific convention is the `tag_field` annotation that was [added to atdgen by @dsheets](https://github.com/mjambon/atdgen/pull/25). Unfortunately, many other conventions also need to be supported. This question was [raised again recently](https://github.com/mjambon/atdgen/issues/70) by users and I encountered it personally. I now have a good solution to that problem, which involves letting the user transform the json tree to make it atd-compliant. Let's call such code "json adapters".

The planned upcoming features for atdgen are:

1. Implement support for json adapters.
2. Emulate the tag_field feature using a json adapter and get rid of its legacy implementation.
3. Eliminate the use of the `Obj` module from all code generated by atdgen for json handling.

(1) was started about a week ago. (3) was started a while ago but stopped due to a lack of resources and because of extra work due to code duplication introduced by tag_field support. Getting rid of `Obj.magic` will reduce maintenance costs and will give users a greater peace of mind, but it's dependent on the simplifications brought by (2).

Please keep in mind that this work is done on my free time, and I don't have much of it. More specifically, I give myself 3 more weekends to get this done (end of April 2018) before returning to other side projects.

**Comment by rgrinberg** [comment]
One thing that I should probably mention is that I've been working on supporting bucklescript (#20) and my branch contains some changes to the codebase. Nothing major, but a fair amount of cruft and duplicate code removal. I've been ferrying patches from it to master as convenient, but given that you're also actively working on the codebase. It would be better if my work didn't diverge too much from yours to avoid painful conflict resolution.

I'll make a PR out of my WIP, and you can judge the some of the changes for yourself. I can start ferrying other changes more actively as well.

**Comment by mjambon** [comment]
Thanks for the heads up.

**Comment by mjambon** [comment]
I added a test that exercises the json adapter feature, and it passes. All the tests having to do with the old `tag_field` feature were removed. Things that remain:
* Offer a runtime library that implements json adapters for common patterns.
* Emulate the `tag_field` feature for backward compatibility.
* Write and publish the documentation for json adapters.

**Comment by mjambon** [comment]
Support for json adapters on records and variants was released today as part of atd 2.0.0.

Eliminating the use `Obj.magic` is now possible without complications. The corresponding task is https://github.com/mjambon/atd/issues/92.
