### ISSUE TITLE
A way to get the unhandled fields in a JSON object?

### ISSUE THREAD

**Issue by brendanlong** [mjambon/atd#57]
I'm using atdgen to parse iCIMS types, and I'd like to make our parsing less specific to our iCIMS integration.

https://developer.icims.com/REST-API/Object-Types-Commands/Profiles

Each type has a set of fields that always exist (id, firstname, lastname, etc.), which I'd like to parse with atdgen, but there's also a set of custom fields, with names like `field1234`. These custom fields are user-specific, and there are thousands of them, so I just want them to be returned as string -> string map.

I can get atdgen to return the whole object as raw JSON, but is there a way for it to parse what it can and then return the rest?

Ideally I'd be able to do something like:

```
let { Icimst.firstname ; lastname ; other } = Icims_j.person_of_string some_string in
let custom =
  List.filter other ~f:(fun (key, _) -> String.has_prefix key ~prefix:"field")
  |> String.Map.of_alist_exn
in
{ first_name = firstname ; last_name = lastname ; custom }
```

**Comment by mjambon** [comment]
The easiest solution is something I'm working on, which I called [json adapters](https://github.com/mjambon/atd/issues/42). It might be ready in a weekend or two. You would write a function that converts the json AST into something that has an atd-compatible structure (and the reverse). Here, you'd move all the fields that start with `field` into a sub-object (or array of pairs) so it conforms to your desired atd/OCaml type:

```ocaml
type person = {
  firstname : string;
  lastname : string;
  ~addresses : address list;
  ...
  custom_fields: (string * json)  (* your json adapter would create this new field *)
}

type json <ocaml module="Yojson.Safe"> = abstract
```

Meanwhile, you may have to write two atd files and say a `person.ml` file that depends on one atd file and is used by the other. The first atd file would contain your desired type definition (like above) and the other one would contain `type person = json wrap <ocaml module="Person">`. This is very complicated, unfortunately.

**Comment by mjambon** [comment]
atd 2.0.0 with support for [json adapters](https://mjambon.github.io/atdgen-doc/atdgen#field-adapter.ocaml) has been released. Let us know if you encounter difficulties.
