### ISSUE TITLE
Unbound value Yojson.Safe.validate_json

### ISSUE THREAD

**Issue by mjambon** [mjambon/atd#97]
_From @vbmithr on December 16, 2015 9:9_

When using, in an `.atd` file,

``` ocaml
type json <ocaml module="Yojson.Safe"> = abstract
```

and using `atdgen -t file.atd`, a call to `Yojson.Safe.validate_json` gets generated. This probably shouldn’t be.

_Copied from original issue: mjambon/atdgen#41_

**Comment by mjambon** [comment]
I assume you mean `atdgen -v file.atd`. This produces `file_v.mli` and `file_v.ml`:

``` ocaml
(* Auto-generated from "file.atd" *)


type json = Yojson.Safe.json

let validate_json = (
  Yojson.Safe.validate_json
)
```

This is the correct behavior. It's just that `Yojson.Safe.validate_json` doesn't exist. It seems to be the only thing that's missing.

The workaround (that I just found in our Esper codebase, yikes) is to create the following json module for yourself and reference it instead of `Yojson.Safe`:

``` ocaml
include Yojson.Safe

let validate_json _ _ = None
```

**Comment by mjambon** [comment]
I added `validate_json` to `Yojson.Safe` and siblings in yojson 1.3.0. https://github.com/mjambon/yojson/compare/v1.2.3...v1.3.0

I think the reason why I didn't do it earlier was that I was fearing a mutual dependency. There's actually no problem since `Yojson.Safe.validate_json` is polymorphic.

**Comment by mjambon** [comment]
opam submission in progress https://github.com/ocaml/opam-repository/pull/5303

**Comment by mjambon** [comment]
_From @vbmithr on December 17, 2015 4:7_

Thanks. I relied on exactly the same workaround :)

**Comment by shonfeder** [comment]
In case it helps future seekers: the fix to Yojson was removed, see https://github.com/ocaml-community/yojson/pull/136. So, iiuc, extending the `Yojson.Safe` as per https://github.com/ahrefs/atd/issues/97#issuecomment-392299012 is the way to do this now.
